export const elemArr = [
  {
    symbol: 'H',
    name: 'Hydrogen',
    mass: 1.008,
    category: 'diatomic nonmetal',
  },
  {
    symbol: 'He',
    name: 'Helium',
    mass: 4.0026022,
    category: 'noble gas',
  },
  {
    symbol: 'Li',
    name: 'Lithium',
    mass: 6.94,
    category: 'alkali metal',
  },
  {
    symbol: 'Be',
    name: 'Beryllium',
    mass: 9.01218315,
    category: 'alkaline earth metal',
  },
  {
    symbol: 'B',
    name: 'Boron',
    mass: 10.81,
    category: 'metalloid',
  },
  {
    symbol: 'C',
    name: 'Carbon',
    mass: 12.011,
    category: 'polyatomic nonmetal',
  },
  {
    symbol: 'N',
    name: 'Nitrogen',
    mass: 14.007,
    category: 'diatomic nonmetal',
  },
  {
    symbol: 'O',
    name: 'Oxygen',
    mass: 15.999,
    category: 'diatomic nonmetal',
  },
  {
    symbol: 'F',
    name: 'Fluorine',
    mass: 18.9984031636,
    category: 'diatomic nonmetal',
  },
  {
    symbol: 'Ne',
    name: 'Neon',
    mass: 20.17976,
    category: 'noble gas',
  },
  {
    symbol: 'Na',
    name: 'Sodium',
    mass: 22.989769282,
    category: 'alkali metal',
  },
  {
    symbol: 'Mg',
    name: 'Magnesium',
    mass: 24.305,
    category: 'alkaline earth metal',
  },
  {
    symbol: 'Al',
    name: 'Aluminium',
    mass: 26.98153857,
    category: 'post-transition metal',
  },
  {
    symbol: 'Si',
    name: 'Silicon',
    mass: 28.085,
    category: 'metalloid',
  },
  {
    symbol: 'P',
    name: 'Phosphorus',
    mass: 30.9737619985,
    category: 'polyatomic nonmetal',
  },
  {
    symbol: 'S',
    name: 'Sulfur',
    mass: 32.06,
    category: 'polyatomic nonmetal',
  },
  {
    symbol: 'Cl',
    name: 'Chlorine',
    mass: 35.45,
    category: 'diatomic nonmetal',
  },
  {
    symbol: 'Ar',
    name: 'Argon',
    mass: 39.9481,
    category: 'noble gas',
  },
  {
    symbol: 'K',
    name: 'Potassium',
    mass: 39.09831,
    category: 'alkali metal',
  },
  {
    symbol: 'Ca',
    name: 'Calcium',
    mass: 40.0784,
    category: 'alkaline earth metal',
  },
  {
    symbol: 'Sc',
    name: 'Scandium',
    mass: 44.9559085,
    category: 'transition metal',
  },
  {
    symbol: 'Ti',
    name: 'Titanium',
    mass: 47.8671,
    category: 'transition metal',
  },
  {
    symbol: 'V',
    name: 'Vanadium',
    mass: 50.94151,
    category: 'transition metal',
  },
  {
    symbol: 'Cr',
    name: 'Chromium',
    mass: 51.99616,
    category: 'transition metal',
  },
  {
    symbol: 'Mn',
    name: 'Manganese',
    mass: 54.9380443,
    category: 'transition metal',
  },
  {
    symbol: 'Fe',
    name: 'Iron',
    mass: 55.8452,
    category: 'transition metal',
  },
  {
    symbol: 'Co',
    name: 'Cobalt',
    mass: 58.9331944,
    category: 'transition metal',
  },
  {
    symbol: 'Ni',
    name: 'Nickel',
    mass: 58.69344,
    category: 'transition metal',
  },
  {
    symbol: 'Cu',
    name: 'Copper',
    mass: 63.5463,
    category: 'transition metal',
  },
  {
    symbol: 'Zn',
    name: 'Zinc',
    mass: 65.382,
    category: 'transition metal',
  },
  {
    symbol: 'Ga',
    name: 'Gallium',
    mass: 69.7231,
    category: 'post-transition metal',
  },
  {
    symbol: 'Ge',
    name: 'Germanium',
    mass: 72.6308,
    category: 'metalloid',
  },
  {
    symbol: 'As',
    name: 'Arsenic',
    mass: 74.9215956,
    category: 'metalloid',
  },
  {
    symbol: 'Se',
    name: 'Selenium',
    mass: 78.9718,
    category: 'polyatomic nonmetal',
  },
  {
    symbol: 'Br',
    name: 'Bromine',
    mass: 79.904,
    category: 'diatomic nonmetal',
  },
  {
    symbol: 'Kr',
    name: 'Krypton',
    mass: 83.7982,
    category: 'noble gas',
  },
  {
    symbol: 'Rb',
    name: 'Rubidium',
    mass: 85.46783,
    category: 'alkali metal',
  },
  {
    symbol: 'Sr',
    name: 'Strontium',
    mass: 87.621,
    category: 'alkaline earth metal',
  },
  {
    symbol: 'Y',
    name: 'Yttrium',
    mass: 88.905842,
    category: 'transition metal',
  },
  {
    symbol: 'Zr',
    name: 'Zirconium',
    mass: 91.2242,
    category: 'transition metal',
  },
  {
    symbol: 'Nb',
    name: 'Niobium',
    mass: 92.906372,
    category: 'transition metal',
  },
  {
    symbol: 'Mo',
    name: 'Molybdenum',
    mass: 95.951,
    category: 'transition metal',
  },
  {
    symbol: 'Tc',
    name: 'Technetium',
    mass: 98,
    category: 'transition metal',
  },
  {
    symbol: 'Ru',
    name: 'Ruthenium',
    mass: 101.072,
    category: 'transition metal',
  },
  {
    symbol: 'Rh',
    name: 'Rhodium',
    mass: 102.905502,
    category: 'transition metal',
  },
  {
    symbol: 'Pd',
    name: 'Palladium',
    mass: 106.421,
    category: 'transition metal',
  },
  {
    symbol: 'Ag',
    name: 'Silver',
    mass: 107.86822,
    category: 'transition metal',
  },
  {
    symbol: 'Cd',
    name: 'Cadmium',
    mass: 112.4144,
    category: 'transition metal',
  },
  {
    symbol: 'In',
    name: 'Indium',
    mass: 114.8181,
    category: 'post-transition metal',
  },
  {
    symbol: 'Sn',
    name: 'Tin',
    mass: 118.7107,
    category: 'post-transition metal',
  },
  {
    symbol: 'Sb',
    name: 'Antimony',
    mass: 121.7601,
    category: 'metalloid',
  },
  {
    symbol: 'Te',
    name: 'Tellurium',
    mass: 127.603,
    category: 'metalloid',
  },
  {
    symbol: 'I',
    name: 'Iodine',
    mass: 126.904473,
    category: 'diatomic nonmetal',
  },
  {
    symbol: 'Xe',
    name: 'Xenon',
    mass: 131.2936,
    category: 'noble gas',
  },
  {
    symbol: 'Cs',
    name: 'Cesium',
    mass: 132.905451966,
    category: 'alkali metal',
  },
  {
    symbol: 'Ba',
    name: 'Barium',
    mass: 137.3277,
    category: 'alkaline earth metal',
  },
  {
    symbol: 'La',
    name: 'Lanthanum',
    mass: 138.905477,
    category: 'lanthanide',
  },
  {
    symbol: 'Ce',
    name: 'Cerium',
    mass: 140.1161,
    category: 'lanthanide',
  },
  {
    symbol: 'Pr',
    name: 'Praseodymium',
    mass: 140.907662,
    category: 'lanthanide',
  },
  {
    symbol: 'Nd',
    name: 'Neodymium',
    mass: 144.2423,
    category: 'lanthanide',
  },
  {
    symbol: 'Pm',
    name: 'Promethium',
    mass: 145,
    category: 'lanthanide',
  },
  {
    symbol: 'Sm',
    name: 'Samarium',
    mass: 150.362,
    category: 'lanthanide',
  },
  {
    symbol: 'Eu',
    name: 'Europium',
    mass: 151.9641,
    category: 'lanthanide',
  },
  {
    symbol: 'Gd',
    name: 'Gadolinium',
    mass: 157.253,
    category: 'lanthanide',
  },
  {
    symbol: 'Tb',
    name: 'Terbium',
    mass: 158.925352,
    category: 'lanthanide',
  },
  {
    symbol: 'Dy',
    name: 'Dysprosium',
    mass: 162.5001,
    category: 'lanthanide',
  },
  {
    symbol: 'Ho',
    name: 'Holmium',
    mass: 164.930332,
    category: 'lanthanide',
  },
  {
    symbol: 'Er',
    name: 'Erbium',
    mass: 167.2593,
    category: 'lanthanide',
  },
  {
    symbol: 'Tm',
    name: 'Thulium',
    mass: 168.934222,
    category: 'lanthanide',
  },
  {
    symbol: 'Yb',
    name: 'Ytterbium',
    mass: 173.0451,
    category: 'lanthanide',
  },
  {
    symbol: 'Lu',
    name: 'Lutetium',
    mass: 174.96681,
    category: 'lanthanide',
  },
  {
    symbol: 'Hf',
    name: 'Hafnium',
    mass: 178.492,
    category: 'transition metal',
  },
  {
    symbol: 'Ta',
    name: 'Tantalum',
    mass: 180.947882,
    category: 'transition metal',
  },
  {
    symbol: 'W',
    name: 'Tungsten',
    mass: 183.841,
    category: 'transition metal',
  },
  {
    symbol: 'Re',
    name: 'Rhenium',
    mass: 186.2071,
    category: 'transition metal',
  },
  {
    symbol: 'Os',
    name: 'Osmium',
    mass: 190.233,
    category: 'transition metal',
  },
  {
    symbol: 'Ir',
    name: 'Iridium',
    mass: 192.2173,
    category: 'transition metal',
  },
  {
    symbol: 'Pt',
    name: 'Platinum',
    mass: 195.0849,
    category: 'transition metal',
  },
  {
    symbol: 'Au',
    name: 'Gold',
    mass: 196.9665695,
    category: 'transition metal',
  },
  {
    symbol: 'Hg',
    name: 'Mercury',
    mass: 200.5923,
    category: 'transition metal',
  },
  {
    symbol: 'Tl',
    name: 'Thallium',
    mass: 204.38,
    category: 'post-transition metal',
  },
  {
    symbol: 'Pb',
    name: 'Lead',
    mass: 207.21,
    category: 'post-transition metal',
  },
  {
    symbol: 'Bi',
    name: 'Bismuth',
    mass: 208.980401,
    category: 'post-transition metal',
  },
  {
    symbol: 'Po',
    name: 'Polonium',
    mass: 209,
    category: 'post-transition metal',
  },
  {
    symbol: 'At',
    name: 'Astatine',
    mass: 210,
    category: 'metalloid',
  },
  {
    symbol: 'Rn',
    name: 'Radon',
    mass: 222,
    category: 'noble gas',
  },
  {
    symbol: 'Fr',
    name: 'Francium',
    mass: 223,
    category: 'alkali metal',
  },
  {
    symbol: 'Ra',
    name: 'Radium',
    mass: 226,
    category: 'alkaline earth metal',
  },
  {
    symbol: 'Ac',
    name: 'Actinium',
    mass: 227,
    category: 'actinide',
  },
  {
    symbol: 'Th',
    name: 'Thorium',
    mass: 232.03774,
    category: 'actinide',
  },
  {
    symbol: 'Pa',
    name: 'Protactinium',
    mass: 231.035882,
    category: 'actinide',
  },
  {
    symbol: 'U',
    name: 'Uranium',
    mass: 238.028913,
    category: 'actinide',
  },
  {
    symbol: 'Np',
    name: 'Neptunium',
    mass: 237,
    category: 'actinide',
  },
  {
    symbol: 'Pu',
    name: 'Plutonium',
    mass: 244,
    category: 'actinide',
  },
  {
    symbol: 'Am',
    name: 'Americium',
    mass: 243,
    category: 'actinide',
  },
  {
    symbol: 'Cm',
    name: 'Curium',
    mass: 247,
    category: 'actinide',
  },
  {
    symbol: 'Bk',
    name: 'Berkelium',
    mass: 247,
    category: 'actinide',
  },
  {
    symbol: 'Cf',
    name: 'Californium',
    mass: 251,
    category: 'actinide',
  },
  {
    symbol: 'Es',
    name: 'Einsteinium',
    mass: 252,
    category: 'actinide',
  },
  {
    symbol: 'Fm',
    name: 'Fermium',
    mass: 257,
    category: 'actinide',
  },
  {
    symbol: 'Md',
    name: 'Mendelevium',
    mass: 258,
    category: 'actinide',
  },
  {
    symbol: 'No',
    name: 'Nobelium',
    mass: 259,
    category: 'actinide',
  },
  {
    symbol: 'Lr',
    name: 'Lawrencium',
    mass: 266,
    category: 'actinide',
  },
  {
    symbol: 'Rf',
    name: 'Rutherfordium',
    mass: 267,
    category: 'transition metal',
  },
  {
    symbol: 'Db',
    name: 'Dubnium',
    mass: 268,
    category: 'transition metal',
  },
  {
    symbol: 'Sg',
    name: 'Seaborgium',
    mass: 269,
    category: 'transition metal',
  },
  {
    symbol: 'Bh',
    name: 'Bohrium',
    mass: 270,
    category: 'transition metal',
  },
  {
    symbol: 'Hs',
    name: 'Hassium',
    mass: 269,
    category: 'transition metal',
  },
  {
    symbol: 'Mt',
    name: 'Meitnerium',
    mass: 278,
    category: 'unknown, probably transition metal',
  },
  {
    symbol: 'Ds',
    name: 'Darmstadtium',
    mass: 281,
    category: 'unknown, probably transition metal',
  },
  {
    symbol: 'Rg',
    name: 'Roentgenium',
    mass: 282,
    category: 'unknown, probably transition metal',
  },
  {
    symbol: 'Cn',
    name: 'Copernicium',
    mass: 285,
    category: 'transition metal',
  },
  {
    symbol: 'Nh',
    name: 'Nihonium',
    mass: 286,
    category: 'unknown, probably transition metal',
  },
  {
    symbol: 'Fl',
    name: 'Flerovium',
    mass: 289,
    category: 'post-transition metal',
  },
  {
    symbol: 'Mc',
    name: 'Moscovium',
    mass: 289,
    category: 'unknown, probably post-transition metal',
  },
  {
    symbol: 'Lv',
    name: 'Livermorium',
    mass: 293,
    category: 'unknown, probably post-transition metal',
  },
  {
    symbol: 'Ts',
    name: 'Tennessine',
    mass: 294,
    category: 'unknown, probably metalloid',
  },
  {
    symbol: 'Og',
    name: 'Oganesson',
    mass: 294,
    category: 'unknown, predicted to be noble gas',
  },
  {
    symbol: 'Uue',
    name: 'Ununennium',
    mass: 315,
    category: 'unknown, but predicted to be an alkali metal',
  },
];
