import { Element } from 'src/periodic-interfaces';

export const elements: {
  [key: string]: Element;
} = {
  H: {
    mass: 1.01,
    number: 1,
    symbol: 'H',
    name: 'Hydrogen',
    category: 'nonmetal',
    color: '#2196F3',
  },
  He: {
    mass: 4,
    number: 2,
    symbol: 'He',
    name: 'Helium',
    category: 'noble gas',
    color: '#009688',
  },
  Li: {
    mass: 6.94,
    number: 3,
    symbol: 'Li',
    name: 'Lithium',
    category: 'alkali metal',
    color: '#F44336',
  },
  Be: {
    mass: 9.01,
    number: 4,
    symbol: 'Be',
    name: 'Beryllium',
    category: 'alkali metal',
    color: '#F44336',
  },
  B: {
    mass: 10.81,
    number: 5,
    symbol: 'B',
    name: 'Boron',
    category: 'metalloid',
    color: '#78909C',
  },
  C: {
    mass: 12.01,
    number: 6,
    symbol: 'C',
    name: 'Carbon',
    category: 'nonmetal',
    color: '#2196F3',
  },
  N: {
    mass: 14.01,
    number: 7,
    symbol: 'N',
    name: 'Nitrogen',
    category: 'nonmetal',
    color: '#2196F3',
  },
  O: {
    mass: 16,
    number: 8,
    symbol: 'O',
    name: 'Oxygen',
    category: 'nonmetal',
    color: '#2196F3',
  },
  F: {
    mass: 19,
    number: 9,
    symbol: 'F',
    name: 'Fluorine',
    category: 'nonmetal',
    color: '#2196F3',
  },
  Ne: {
    mass: 20.18,
    number: 10,
    symbol: 'Ne',
    name: 'Neon',
    category: 'noble gas',
    color: '#009688',
  },
  Na: {
    mass: 22.99,
    number: 11,
    symbol: 'Na',
    name: 'Sodium',
    category: 'alkali metal',
    color: '#F44336',
  },
  Mg: {
    mass: 24.31,
    number: 12,
    symbol: 'Mg',
    name: 'Magnesium',
    category: 'alkali metal',
    color: '#F44336',
  },
  Al: {
    mass: 26.98,
    number: 13,
    symbol: 'Al',
    name: 'Aluminium',
    category: 'metalloid',
    color: '#78909C',
  },
  Si: {
    mass: 28.09,
    number: 14,
    symbol: 'Si',
    name: 'Silicon',
    category: 'metalloid',
    color: '#78909C',
  },
  P: {
    mass: 30.97,
    number: 15,
    symbol: 'P',
    name: 'Phosphorus',
    category: 'nonmetal',
    color: '#2196F3',
  },
  S: {
    mass: 32.06,
    number: 16,
    symbol: 'S',
    name: 'Sulfur',
    category: 'nonmetal',
    color: '#2196F3',
  },
  Cl: {
    mass: 35.45,
    number: 17,
    symbol: 'Cl',
    name: 'Chlorine',
    category: 'nonmetal',
    color: '#2196F3',
  },
  Ar: {
    mass: 39.95,
    number: 18,
    symbol: 'Ar',
    name: 'Argon',
    category: 'noble gas',
    color: '#009688',
  },
  K: {
    mass: 39.1,
    number: 19,
    symbol: 'K',
    name: 'Potassium',
    category: 'alkali metal',
    color: '#F44336',
  },
  Ca: {
    mass: 40.08,
    number: 20,
    symbol: 'Ca',
    name: 'Calcium',
    category: 'alkali metal',
    color: '#F44336',
  },
  Sc: {
    mass: 44.96,
    number: 21,
    symbol: 'Sc',
    name: 'Scandium',
    category: 'transition metal',
    color: '#673AB7',
  },
  Ti: {
    mass: 47.87,
    number: 22,
    symbol: 'Ti',
    name: 'Titanium',
    category: 'transition metal',
    color: '#673AB7',
  },
  V: {
    mass: 50.94,
    number: 23,
    symbol: 'V',
    name: 'Vanadium',
    category: 'transition metal',
    color: '#673AB7',
  },
  Cr: {
    mass: 52,
    number: 24,
    symbol: 'Cr',
    name: 'Chromium',
    category: 'transition metal',
    color: '#673AB7',
  },
  Mn: {
    mass: 54.94,
    number: 25,
    symbol: 'Mn',
    name: 'Manganese',
    category: 'transition metal',
    color: '#673AB7',
  },
  Fe: {
    mass: 55.85,
    number: 26,
    symbol: 'Fe',
    name: 'Iron',
    category: 'transition metal',
    color: '#673AB7',
  },
  Co: {
    mass: 58.93,
    number: 27,
    symbol: 'Co',
    name: 'Cobalt',
    category: 'transition metal',
    color: '#673AB7',
  },
  Ni: {
    mass: 58.69,
    number: 28,
    symbol: 'Ni',
    name: 'Nickel',
    category: 'transition metal',
    color: '#673AB7',
  },
  Cu: {
    mass: 63.55,
    number: 29,
    symbol: 'Cu',
    name: 'Copper',
    category: 'transition metal',
    color: '#673AB7',
  },
  Zn: {
    mass: 65.38,
    number: 30,
    symbol: 'Zn',
    name: 'Zinc',
    category: 'transition metal',
    color: '#673AB7',
  },
  Ga: {
    mass: 69.72,
    number: 31,
    symbol: 'Ga',
    name: 'Gallium',
    category: 'metalloid',
    color: '#78909C',
  },
  Ge: {
    mass: 72.63,
    number: 32,
    symbol: 'Ge',
    name: 'Germanium',
    category: 'metalloid',
    color: '#78909C',
  },
  As: {
    mass: 74.92,
    number: 33,
    symbol: 'As',
    name: 'Arsenic',
    category: 'metalloid',
    color: '#78909C',
  },
  Se: {
    mass: 78.97,
    number: 34,
    symbol: 'Se',
    name: 'Selenium',
    category: 'nonmetal',
    color: '#2196F3',
  },
  Br: {
    mass: 79.9,
    number: 35,
    symbol: 'Br',
    name: 'Bromine',
    category: 'nonmetal',
    color: '#2196F3',
  },
  Kr: {
    mass: 83.8,
    number: 36,
    symbol: 'Kr',
    name: 'Krypton',
    category: 'noble gas',
    color: '#009688',
  },
  Rb: {
    mass: 85.47,
    number: 37,
    symbol: 'Rb',
    name: 'Rubidium',
    category: 'alkali metal',
    color: '#F44336',
  },
  Sr: {
    mass: 87.62,
    number: 38,
    symbol: 'Sr',
    name: 'Strontium',
    category: 'alkali metal',
    color: '#F44336',
  },
  Y: {
    mass: 88.91,
    number: 39,
    symbol: 'Y',
    name: 'Yttrium',
    category: 'transition metal',
    color: '#673AB7',
  },
  Zr: {
    mass: 91.22,
    number: 40,
    symbol: 'Zr',
    name: 'Zirconium',
    category: 'transition metal',
    color: '#673AB7',
  },
  Nb: {
    mass: 92.91,
    number: 41,
    symbol: 'Nb',
    name: 'Niobium',
    category: 'transition metal',
    color: '#673AB7',
  },
  Mo: {
    mass: 95.95,
    number: 42,
    symbol: 'Mo',
    name: 'Molybdenum',
    category: 'transition metal',
    color: '#673AB7',
  },
  Tc: {
    mass: 98,
    number: 43,
    symbol: 'Tc',
    name: 'Technetium',
    category: 'transition metal',
    color: '#673AB7',
  },
  Ru: {
    mass: 101.07,
    number: 44,
    symbol: 'Ru',
    name: 'Ruthenium',
    category: 'transition metal',
    color: '#673AB7',
  },
  Rh: {
    mass: 102.91,
    number: 45,
    symbol: 'Rh',
    name: 'Rhodium',
    category: 'transition metal',
    color: '#673AB7',
  },
  Pd: {
    mass: 106.42,
    number: 46,
    symbol: 'Pd',
    name: 'Palladium',
    category: 'transition metal',
    color: '#673AB7',
  },
  Ag: {
    mass: 107.87,
    number: 47,
    symbol: 'Ag',
    name: 'Silver',
    category: 'transition metal',
    color: '#673AB7',
  },
  Cd: {
    mass: 112.41,
    number: 48,
    symbol: 'Cd',
    name: 'Cadmium',
    category: 'transition metal',
    color: '#673AB7',
  },
  In: {
    mass: 114.82,
    number: 49,
    symbol: 'In',
    name: 'Indium',
    category: 'metalloid',
    color: '#78909C',
  },
  Sn: {
    mass: 118.71,
    number: 50,
    symbol: 'Sn',
    name: 'Tin',
    category: 'metalloid',
    color: '#78909C',
  },
  Sb: {
    mass: 121.76,
    number: 51,
    symbol: 'Sb',
    name: 'Antimony',
    category: 'metalloid',
    color: '#78909C',
  },
  Te: {
    mass: 127.6,
    number: 52,
    symbol: 'Te',
    name: 'Tellurium',
    category: 'metalloid',
    color: '#78909C',
  },
  I: {
    mass: 126.9,
    number: 53,
    symbol: 'I',
    name: 'Iodine',
    category: 'nonmetal',
    color: '#2196F3',
  },
  Xe: {
    mass: 131.29,
    number: 54,
    symbol: 'Xe',
    name: 'Xenon',
    category: 'noble gas',
    color: '#009688',
  },
  Cs: {
    mass: 132.91,
    number: 55,
    symbol: 'Cs',
    name: 'Cesium',
    category: 'alkali metal',
    color: '#F44336',
  },
  Ba: {
    mass: 137.33,
    number: 56,
    symbol: 'Ba',
    name: 'Barium',
    category: 'alkali metal',
    color: '#F44336',
  },
  La: {
    mass: 138.91,
    number: 57,
    symbol: 'La',
    name: 'Lanthanum',
    category: 'lanthanide_actinide',
    color: '#8D6E63',
  },
  Ce: {
    mass: 140.12,
    number: 58,
    symbol: 'Ce',
    name: 'Cerium',
    category: 'lanthanide_actinide',
    color: '#8D6E63',
  },
  Pr: {
    mass: 140.91,
    number: 59,
    symbol: 'Pr',
    name: 'Praseodymium',
    category: 'lanthanide_actinide',
    color: '#8D6E63',
  },
  Nd: {
    mass: 144.24,
    number: 60,
    symbol: 'Nd',
    name: 'Neodymium',
    category: 'lanthanide_actinide',
    color: '#8D6E63',
  },
  Pm: {
    mass: 145,
    number: 61,
    symbol: 'Pm',
    name: 'Promethium',
    category: 'lanthanide_actinide',
    color: '#8D6E63',
  },
  Sm: {
    mass: 150.36,
    number: 62,
    symbol: 'Sm',
    name: 'Samarium',
    category: 'lanthanide_actinide',
    color: '#8D6E63',
  },
  Eu: {
    mass: 151.96,
    number: 63,
    symbol: 'Eu',
    name: 'Europium',
    category: 'lanthanide_actinide',
    color: '#8D6E63',
  },
  Gd: {
    mass: 157.25,
    number: 64,
    symbol: 'Gd',
    name: 'Gadolinium',
    category: 'lanthanide_actinide',
    color: '#8D6E63',
  },
  Tb: {
    mass: 158.93,
    number: 65,
    symbol: 'Tb',
    name: 'Terbium',
    category: 'lanthanide_actinide',
    color: '#8D6E63',
  },
  Dy: {
    mass: 162.5,
    number: 66,
    symbol: 'Dy',
    name: 'Dysprosium',
    category: 'lanthanide_actinide',
    color: '#8D6E63',
  },
  Ho: {
    mass: 164.93,
    number: 67,
    symbol: 'Ho',
    name: 'Holmium',
    category: 'lanthanide_actinide',
    color: '#8D6E63',
  },
  Er: {
    mass: 167.26,
    number: 68,
    symbol: 'Er',
    name: 'Erbium',
    category: 'lanthanide_actinide',
    color: '#8D6E63',
  },
  Tm: {
    mass: 168.93,
    number: 69,
    symbol: 'Tm',
    name: 'Thulium',
    category: 'lanthanide_actinide',
    color: '#8D6E63',
  },
  Yb: {
    mass: 173.05,
    number: 70,
    symbol: 'Yb',
    name: 'Ytterbium',
    category: 'lanthanide_actinide',
    color: '#8D6E63',
  },
  Lu: {
    mass: 174.97,
    number: 71,
    symbol: 'Lu',
    name: 'Lutetium',
    category: 'lanthanide_actinide',
    color: '#8D6E63',
  },
  Hf: {
    mass: 178.49,
    number: 72,
    symbol: 'Hf',
    name: 'Hafnium',
    category: 'transition metal',
    color: '#673AB7',
  },
  Ta: {
    mass: 180.95,
    number: 73,
    symbol: 'Ta',
    name: 'Tantalum',
    category: 'transition metal',
    color: '#673AB7',
  },
  W: {
    mass: 183.84,
    number: 74,
    symbol: 'W',
    name: 'Tungsten',
    category: 'transition metal',
    color: '#673AB7',
  },
  Re: {
    mass: 186.21,
    number: 75,
    symbol: 'Re',
    name: 'Rhenium',
    category: 'transition metal',
    color: '#673AB7',
  },
  Os: {
    mass: 190.23,
    number: 76,
    symbol: 'Os',
    name: 'Osmium',
    category: 'transition metal',
    color: '#673AB7',
  },
  Ir: {
    mass: 192.22,
    number: 77,
    symbol: 'Ir',
    name: 'Iridium',
    category: 'transition metal',
    color: '#673AB7',
  },
  Pt: {
    mass: 195.08,
    number: 78,
    symbol: 'Pt',
    name: 'Platinum',
    category: 'transition metal',
    color: '#673AB7',
  },
  Au: {
    mass: 196.97,
    number: 79,
    symbol: 'Au',
    name: 'Gold',
    category: 'transition metal',
    color: '#673AB7',
  },
  Hg: {
    mass: 200.59,
    number: 80,
    symbol: 'Hg',
    name: 'Mercury',
    category: 'transition metal',
    color: '#673AB7',
  },
  Tl: {
    mass: 204.38,
    number: 81,
    symbol: 'Tl',
    name: 'Thallium',
    category: 'metalloid',
    color: '#78909C',
  },
  Pb: {
    mass: 207.21,
    number: 82,
    symbol: 'Pb',
    name: 'Lead',
    category: 'metalloid',
    color: '#78909C',
  },
  Bi: {
    mass: 208.98,
    number: 83,
    symbol: 'Bi',
    name: 'Bismuth',
    category: 'metalloid',
    color: '#78909C',
  },
  Po: {
    mass: 209,
    number: 84,
    symbol: 'Po',
    name: 'Polonium',
    category: 'metalloid',
    color: '#78909C',
  },
  At: {
    mass: 210,
    number: 85,
    symbol: 'At',
    name: 'Astatine',
    category: 'metalloid',
    color: '#78909C',
  },
  Rn: {
    mass: 222,
    number: 86,
    symbol: 'Rn',
    name: 'Radon',
    category: 'noble gas',
    color: '#009688',
  },
  Fr: {
    mass: 223,
    number: 87,
    symbol: 'Fr',
    name: 'Francium',
    category: 'alkali metal',
    color: '#F44336',
  },
  Ra: {
    mass: 226,
    number: 88,
    symbol: 'Ra',
    name: 'Radium',
    category: 'alkali metal',
    color: '#F44336',
  },
  Ac: {
    mass: 227,
    number: 89,
    symbol: 'Ac',
    name: 'Actinium',
    category: 'lanthanide_actinide',
    color: '#8D6E63',
  },
  Th: {
    mass: 232.04,
    number: 90,
    symbol: 'Th',
    name: 'Thorium',
    category: 'lanthanide_actinide',
    color: '#8D6E63',
  },
  Pa: {
    mass: 231.04,
    number: 91,
    symbol: 'Pa',
    name: 'Protactinium',
    category: 'lanthanide_actinide',
    color: '#8D6E63',
  },
  U: {
    mass: 238.03,
    number: 92,
    symbol: 'U',
    name: 'Uranium',
    category: 'lanthanide_actinide',
    color: '#8D6E63',
  },
  Np: {
    mass: 237,
    number: 93,
    symbol: 'Np',
    name: 'Neptunium',
    category: 'lanthanide_actinide',
    color: '#8D6E63',
  },
  Pu: {
    mass: 244,
    number: 94,
    symbol: 'Pu',
    name: 'Plutonium',
    category: 'lanthanide_actinide',
    color: '#8D6E63',
  },
  Am: {
    mass: 243,
    number: 95,
    symbol: 'Am',
    name: 'Americium',
    category: 'lanthanide_actinide',
    color: '#8D6E63',
  },
  Cm: {
    mass: 247,
    number: 96,
    symbol: 'Cm',
    name: 'Curium',
    category: 'lanthanide_actinide',
    color: '#8D6E63',
  },
  Bk: {
    mass: 247,
    number: 97,
    symbol: 'Bk',
    name: 'Berkelium',
    category: 'lanthanide_actinide',
    color: '#8D6E63',
  },
  Cf: {
    mass: 251,
    number: 98,
    symbol: 'Cf',
    name: 'Californium',
    category: 'lanthanide_actinide',
    color: '#8D6E63',
  },
  Es: {
    mass: 252,
    number: 99,
    symbol: 'Es',
    name: 'Einsteinium',
    category: 'lanthanide_actinide',
    color: '#8D6E63',
  },
  Fm: {
    mass: 257,
    number: 100,
    symbol: 'Fm',
    name: 'Fermium',
    category: 'lanthanide_actinide',
    color: '#8D6E63',
  },
  Md: {
    mass: 258,
    number: 101,
    symbol: 'Md',
    name: 'Mendelevium',
    category: 'lanthanide_actinide',
    color: '#8D6E63',
  },
  No: {
    mass: 259,
    number: 102,
    symbol: 'No',
    name: 'Nobelium',
    category: 'lanthanide_actinide',
    color: '#8D6E63',
  },
  Lr: {
    mass: 266,
    number: 103,
    symbol: 'Lr',
    name: 'Lawrencium',
    category: 'lanthanide_actinide',
    color: '#8D6E63',
  },
  Rf: {
    mass: 267,
    number: 104,
    symbol: 'Rf',
    name: 'Rutherfordium',
    category: 'transition metal',
    color: '#673AB7',
  },
  Db: {
    mass: 268,
    number: 105,
    symbol: 'Db',
    name: 'Dubnium',
    category: 'transition metal',
    color: '#673AB7',
  },
  Sg: {
    mass: 269,
    number: 106,
    symbol: 'Sg',
    name: 'Seaborgium',
    category: 'transition metal',
    color: '#673AB7',
  },
  Bh: {
    mass: 270,
    number: 107,
    symbol: 'Bh',
    name: 'Bohrium',
    category: 'transition metal',
    color: '#673AB7',
  },
  Hs: {
    mass: 269,
    number: 108,
    symbol: 'Hs',
    name: 'Hassium',
    category: 'transition metal',
    color: '#673AB7',
  },
  Cn: {
    mass: 285,
    number: 112,
    symbol: 'Cn',
    name: 'Copernicium',
    category: 'transition metal',
    color: '#673AB7',
  },
  Fl: {
    mass: 289,
    number: 114,
    symbol: 'Fl',
    name: 'Flerovium',
    category: 'metalloid',
    color: '#78909C',
  },
};
